RUN_SERVER = 0
DATABASE_URI = 'mssql+pymssql://DESKTOP-98F3HH3/OddShark'
GOOGLE_SPREAD_SHEET_CREDENTIAL = 'test1-3301c1f1cf08.json'
GOOGLE_SPREAD_SHEET_NAME = 'Shane_Sports_Betting_Data'
SHARE_EMAIL = 'shanehvizdzak@gmail.com'
AIRTABLE_API_KEY = 'keymkZI6p1c5Pjk2L'
AIRTABLE_BASE_KEY = 'appBHoFGUaQ0ufuMb'
LOCAL_AIRTABLE_BASE_KEY = 'appHY5tTEe3WEL328'

